const ALIMENTACAO = "ALIMENTACAO"; 
const SAUDE = "SAUDE"; 
const MORADIA = "MORADIA"; 
const TRANSPORTE = "TRANSPORTE"; 
const EDUCACAO = "EDUCACAO"; 
const LAZER = "LAZER"; 
const IMPREVISTOS = "IMPREVISTOS"; 
const OUTRAS = "OUTRAS";

export { ALIMENTACAO, SAUDE, MORADIA, TRANSPORTE, EDUCACAO, LAZER, IMPREVISTOS, OUTRAS }
